[package]
name = "day_12"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "bench_day_12"
harness = false